[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#f5f5f5"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#2d2d2d"
textColor = "#f5f5f5"
font = "sans serif"

[ui]
hideTopBar = false
hideSidebarNav = false